### ISSUE TITLE
怎么用?

### ISSUE THREAD

**Issue by 120520** [zhoumingque/LabelX#3]
有教程或文档吗

**Comment by rickyes** [comment]
在common文件夹里面添加controller（对应router），service（是访问数据库的服务），servers（是socket服务），添加接口在router文件夹下新建一个一级路由，然后在里面添加子路由

**Comment by 120520** [comment]
框架里的redis和mysql有联系起来吗?

**Comment by rickyes** [comment]
没有直接联系，只是游戏开始的时候需要频繁io，所以就把游戏进行中的数据保存在redis中，游戏结束再更新到mysql

**Comment by 120520** [comment]
怪不得,我看到框架中有标注mysql持久化服务,但没看到哪一步做了关联,还以为少download了什么文件
